telegram:
  botName: ***
  token: ***
spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-test-query: select 1
      connection-timeout: 1000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 180000
      driver-class-name: org.postgresql.Driver
      jdbc-url: ***
      username: ***
      password: ***
server:
  port: ***
admin:
  id: [***, ***]
