telegram:
  botName: MyPenetrationBot
  token: 5804316353:AAFyFKzrpP6d5VdkX0-K8at6bwBr3VT6Dz4
spring:
  h2:
    console:
      enabled: true
      path: /gadget-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: sa
    password: 111
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
server:
  port: 8090